- Handle mailman executables in /usr/lib/mailmna/bin (previously /var/lib/mailman/bin) - Allow for multiple patch files in "version.d" directory

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -8,8 +8,15 @@ MAILMAN_SCRIPT="/var/lib/mailman/mail/mailman"
 MAILMAN_CONFIG="/etc/mailman/mm_cfg.py"
 MAILMAN_CONFIG_TEMPLATE="/etc/alternc/templates/mailman/mm_cfg.py"
 MAILMAN_CONFIG_BACKUP="/var/backups/alternc/etc-mailman-mm_cfg.py"
-MAILMAN_SCRIPT="/var/lib/mailman/mail/mailman"
 MAILMAN_PASS="`perl -e 'print map{("a".."z","A".."Z",0..9)[int(rand(62))]}(1..10)' `" # copy-pasted from alternc/debian/config
+
+# new packages put binaries in /usr/lib/mailman/bin
+if [ -d /usr/lib/mailman/bin ]
+then
+    MAILMAN_BIN="/usr/lib/mailman/bin"
+else
+    MAILMAN_BIN="/var/lib/mailman/bin"
+fi
 
 case "$1" in
   configure)
@@ -33,10 +40,15 @@ case "$1" in
 
     MAILMAN_VERSION=`dpkg -l mailman | grep ^ii | awk '{print $3}' | sed -e s/-.*// -e 's/[^:]*://'`
     echo "detected mailman version $MAILMAN_VERSION"
-    PATCHFILE="/usr/share/alternc-mailman/patches/mailman-true-virtual-$MAILMAN_VERSION.patch"
+    if [ -d "/usr/share/alternc-mailman/patches/mailman-true-virtual-$MAILMAN_VERSION.d" ] ; then
+      PATCHDIR="/usr/share/alternc-mailman/patches/mailman-true-virtual-$MAILMAN_VERSION.d"
+    else
+      PATCHDIR=""
+      PATCHFILE="/usr/share/alternc-mailman/patches/mailman-true-virtual-$MAILMAN_VERSION.patch"
+    fi
     PATCH_MARKER="/usr/share/alternc-mailman/patches/mailman-true-virtual.applied"
     if [ -h $PATCH_MARKER ]; then
-        PATCH_VERSION=`readlink $PATCH_MARKER | sed -e 's/^.*-//;s/\.patch//'`
+        PATCH_VERSION=`readlink $PATCH_MARKER | sed -e 's/^.*-//;s/\.patch$//;s/\.d$//'`
         echo "mailman patch detected, version $PATCH_VERSION"
         if [ "$PATCH_VERSION" = "$MAILMAN_VERSION" ]; then
             echo "mailman already patched, will not patch again"
@@ -45,12 +57,40 @@ case "$1" in
             rm -f $PATCH_MARKER
         fi
     fi
-    if [ ! -r $PATCHFILE ]; then
-        echo "no patchfile for mailman $MAILMAN_VERSION"
+    if [ "$PATCHDIR" = "" ] ; then
+        if [ ! -r $PATCHFILE ]; then
+            echo "no patchfile for mailman $MAILMAN_VERSION"
+        fi
     fi
-    if [ -r $PATCHFILE -a ! -h $PATCH_MARKER ]; then
+    if [ -r "$PATCHFILE" -o  "$PATCHDIR" != "" ] ; then if [ ! -h $PATCH_MARKER ]; then
         db_get alternc-mailman/patch-mailman || true
         if [ "$RET" = "true" ]; then
+            if [ "$PATCHDIR" != "" ] ; then # we have multiple files
+            {
+                cd /        # patches should be relative to root, now
+                patch_ok="yes"
+                for pfile in $PATCHDIR/* ; do
+                    if patch --dry-run -p0 < $pfile; then
+                        echo "applying patch $pfile :"
+                        if patch -p0 < $pfile; then
+                            echo "patch applied sucessfully"
+                        else
+                            patch_ok="no"
+                            echo "cannot apply patch, your mailman is probably broken now, aborting"
+                            false
+                        fi
+                    else
+                        echo "patch will not apply cleanly, aborting"
+                        patch_ok="no"
+                    fi
+                    if [ "$patch_ok" = "yes" ] ; then
+                        # this will tell alternc-mailman the patch was applied successfully
+                        ln -fs $PATCHDIR $PATCH_MARKER
+                        invoke-rc.d mailman restart || true
+                    fi
+                done
+            }
+            else # old fashion unique patch file
             {
                 cd /var/lib
                 echo "testing the patch"
@@ -69,6 +109,7 @@ case "$1" in
                     echo "patch will not apply cleanly, aborting"
                 fi
             }
+            fi ; fi
         else
             echo "not applying virtual mailman patch"
         fi
@@ -78,7 +119,7 @@ case "$1" in
 
     # Create the "mailman" list if it does not exist yet
     if [ ! -d /var/lib/mailman/lists/mailman ]; then
-        /var/lib/mailman/bin/newlist -q mailman "root@$FQDN" "${MAILMAN_PASS}"
+        ${MAILMAN_BIN}/newlist -q mailman "root@$FQDN" "${MAILMAN_PASS}"
         ( echo "INSERT INTO mailman SET id=NULL, uid=2000, list='mailman', domain='${FQDN}', name='mailman';"
           echo "INSERT INTO mail_domain SET mail='mailman@${FQDN}', alias='mailman_${FQDN}', uid=2000, pop=0, type=1;"
           echo "INSERT INTO mail_alias SET mail='mailman_${FQDN}', alias='\"| $MAILMAN_SCRIPT post mailman\"';"
@@ -91,7 +132,7 @@ case "$1" in
     fi
 
     ln -sf /usr/lib/cgi-bin/mailman /var/alternc/cgi-bin/mailman
-    alternc.install
+    alternc.install || true         # don't fail package config if alternc.install bails out
 
     # ADD Mailman menu item : 
     if ! grep -q "^menu_mailman.php$" "$MENUFILE"; then
